/// Flutter icons BluetoothMicIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BluetoothMicIcon
///      fonts:
///       - asset: fonts/BluetoothMicIcon.ttf
///
///
///
part of 'assets_strings.dart';

// abstract class BluetoothMicIcon {
//   static const androidFill = 'assets/images/bluetooth_mic_icon/android_fill.png';
//   static const androidOutlined = 'assets/images/bluetooth_mic_icon/android_outlined.png';
//   static const appleFill = 'assets/images/bluetooth_mic_icon/ios_fill.png';
//   static const appleOutlined = 'assets/images/bluetooth_mic_icon/ios_outlined.png';
// }
abstract class BluetoothMicIcon {
  static const _fontFamily = 'BluetoothMicIcon';

  static const IconData androidFilled = IconData(0xe803, fontFamily: _fontFamily);
  static const IconData androidOutlined = IconData(0xe800, fontFamily: _fontFamily);
  static const IconData iosFilled = IconData(0xe801, fontFamily: _fontFamily);
  static const IconData iosOutlined = IconData(0xe802, fontFamily: _fontFamily);
}
