// enum StyleType {
//   displayLarge,
//   displayMedium,
//   displaySmall,
//   headlineLarge,
//   headlineMedium,
//   headlineSmall,
//   titleLarge,
//   titleMedium,
//   titleSmall,
//   bodyLarge,
//   bodyMedium,
//   bodySmall,
//   labelLarge,
//   labelMedium,
//   labelSmall;
//
//   TextStyle origStyle(WidgetRef ref) => switch (this) {
//     StyleType.displayLarge => LiveData.textTheme(ref).displayLarge!,
//     StyleType.displayMedium => LiveData.textTheme(ref).displayMedium!,
//     StyleType.displaySmall => LiveData.textTheme(ref).displaySmall!,
//     StyleType.headlineLarge => LiveData.textTheme(ref).headlineLarge!,
//     StyleType.headlineMedium => LiveData.textTheme(ref).headlineMedium!,
//     StyleType.headlineSmall => LiveData.textTheme(ref).headlineSmall!,
//     StyleType.titleLarge => LiveData.textTheme(ref).titleLarge!,
//     StyleType.titleMedium => LiveData.textTheme(ref).titleMedium!,
//     StyleType.titleSmall => LiveData.textTheme(ref).titleSmall!,
//     StyleType.bodyLarge => LiveData.textTheme(ref).bodyLarge!,
//     StyleType.bodyMedium => LiveData.textTheme(ref).bodyMedium!,
//     StyleType.bodySmall => LiveData.textTheme(ref).bodySmall!,
//     StyleType.labelLarge => LiveData.textTheme(ref).labelLarge!,
//     StyleType.labelMedium => LiveData.textTheme(ref).labelMedium!,
//     StyleType.labelSmall => LiveData.textTheme(ref).labelSmall!,
//   };
// }
